/* eslint-disable prettier/prettier */
import type { NextPage } from "next"
import Head from "next/head"

import HomePage from "./Homepage/Homepage"

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Formulário de compra</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<HomePage />
		</div>
	)
}

export default Home
