/* eslint-disable prettier/prettier */
import type { NextPage } from "next"
import Head from "next/head"
import MyCheckBox from "../components/CheckBox/Checkbox"
import { CheckboxDiv } from "../components/CheckBox"
import MyRadio from "../components/Radio/Radio"
import { RadioDiv } from "../components/Radio"

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CheckboxDiv>
				<MyCheckBox name="React" />
				<MyCheckBox name="React" />
				<MyCheckBox name="React" />
			</CheckboxDiv>
			<RadioDiv>
				<MyRadio name="P" />
				<MyRadio name="M" />
				<MyRadio name="G" />
			</RadioDiv>
		</div>
	)
}

export default Home
